Repository cognitedata/cognite-remote-web-configurator, pull requests merged in 2020-12, with the labels that each got.

#48 Insert Array Items
  .gitignore
  package-lock.json
  src/components/JsonEditorContainer/JsonEditorContainer.tsx
Labels: sub-task

#49 Adding items to array and map
  src/components/JsonEditor/JsonEditor.tsx
  src/components/JsonEditorContainer/JsonEditorContainer.tsx
Labels: sub-task

#57 Handle read only
  src/userInterface/components/JsonEditorContainer/JsonEditorContainer.tsx
  src/validator/util/Helper.ts
Labels: feature

#65 Gayan/create new twin
  package-lock.json
  package.json
  src/core/Api.ts
  src/core/CogniteJsonEditorOptions.ts
  src/core/DigitalTwinApi.ts
  src/core/JsonConfigCommandCenter.ts
  src/userInterface/components/CommandItem/CommandItem.module.scss
  src/userInterface/components/ConfigSelector/ConfigSelector.module.scss
  src/userInterface/components/ConfigSelector/ConfigSelector.tsx
  src/userInterface/panels/CommandPanel/CommandPanel.module.scss
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.module.scss
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.tsx
  src/userInterface/panels/SideNavPanel/SideNavPanel.module.scss
  src/userInterface/panels/SideNavPanel/SideNavPanel.tsx
  src/userInterface/util/Interfaces/CommandEvent.ts
  yarn.lock
Labels: sub-task

#83 Populate example json values
  src/core/CogniteJsonEditorOptions.ts
  src/validator/Validator.ts
  src/validator/nodes/BaseNode.ts
  src/validator/nodes/MapNode.ts
  src/validator/util/Helper.ts
  src/validator/util/NodeFactory.ts
Labels: feature

#78 Alerts of CRUD
  package-lock.json
  package.json
  src/constants.ts
  src/core/CogniteJsonEditorOptions.ts
  src/core/DigitalTwinApi.ts
  src/core/JsonConfigCommandCenter.ts
  src/userInterface/components/ConfigSelector/ConfigSelector.tsx
  src/userInterface/components/CustomLogin/CustomLogin.tsx
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.tsx
Labels: feature

#90 fix child discriminator errors not showing, value and type validation
  package.json
  src/constants.ts
  src/core/CogniteJsonEditorOptions.ts
  src/core/JsonConfigCommandCenter.ts
  yarn.lock
Labels: bug

#93 min max numbe fix,config list color and mode switch change
  src/core/CogniteJsonEditorOptions.ts
  src/userInterface/components/ConfigSelector/ConfigSelector.module.scss
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
Labels: bug
