Repository cognitedata/cognite-remote-web-configurator, pull requests merged in 2021-01, with the labels that each got.

#125 Concurrent User Support
  package.json
  public/index.html
  src/constants.ts
  src/core/CogniteJsonEditorOptions.ts
  src/core/DigitalTwinApi.ts
  src/core/JsonConfigCommandCenter.ts
  src/core/enums/AutoCompleteElementType.ts
  src/core/validator/CogniteOpenApiSchemaValidator.ts
  src/userInterface/App.scss
  src/userInterface/components/ConfigSelector/ConfigSelector.tsx
  src/userInterface/components/DiffMerge/DiffMerge.module.scss
  src/userInterface/components/DiffMerge/DiffMerge.tsx
  src/userInterface/components/TenantLogin/TenantLogin.tsx
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.module.scss
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.tsx
  src/userInterface/panels/SideNavPanel/SideNavPanel.module.scss
  src/userInterface/panels/SideNavPanel/SideNavPanel.tsx
  src/userInterface/util/Interfaces/CommandEvent.ts
  src/userInterface/util/types.ts
  yarn.lock
Labels: feature

#140 Popup Messages
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
Labels: enahancement

#147 Show config schema error warning
  debug.log
  src/core/JsonConfigCommandCenter.ts
  src/userInterface/panels/CommandPanel/CommandPanel.module.scss
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/validator/Validator.ts
Labels: enahancement

#164 Save without a name
  src/constants.ts
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
Labels: sub feature

#174 fix for reloading after new config removes changes and fix deletion doesn't reset text
  src/core/JsonConfigCommandCenter.ts
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.tsx
Labels: bug

#182 Fix Refresh Cancel
  src/userInterface/panels/CommandPanel/CommandPanel.tsx
  src/userInterface/panels/JsonConfigurator/JsonConfigurator.tsx
Labels: bug
